micronaut:
  application:
    name: key-manager

grpc:
  server:
    port: 55051
    keep-alive-time: 3h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:mysql://localhost:3306/keyManager?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update


