micronaut:
  application:
    name: key-manager

grpc:
  server:
    port: ${PORT_GRPC:55051}
    keep-alive-time: 3h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:mysql://${DATASOURCE_URL:`localhost:3306`}/keyManager?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:`root`}
    password: ${DATASOURCE_USERNAME:`root`}
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: update

proxy:
  client:
    itau:  ${ITAU_PROXY_URL:`http://localhost:9091/api/v1`}
    bcb: ${BCB_PROXY_URL:`http://localhost:8082/api/v1`}